### ISSUE TITLE
In memory.go you are using lock.RLock for both reads and writes

### ISSUE THREAD

**Issue by raff** [adelowo/onecache#10]
You should be using lock.Lock() for writes (Set, Delete, etc.) and lock.RLock() for reads (Get)

See https://github.com/adelowo/onecache/blob/master/memory/memory.go#L24 and https://github.com/adelowo/onecache/blob/master/memory/memory.go#L41

Otherwise use a regular sync.Mutex()

**Comment by adelowo** [comment]
Oh, thanks a lot.. I think i should just make use of a regular mutex since that does the job properly too, right ?

**Comment by raff** [comment]
It depends on how "fast" you want your code to be.

If you don't think this needs to be very performant (or you are expecting single reader/single writer usage), using a regular mutex for reads and writes it's fine.

If you are expecting use cases where there are multiple readers that can access the data concurrently, then you want to use a read/write lock. In this case when you use lock.RLock() you lock the resource for reads (that means, other clients can read, but writes will have to wait), then you use lock.Lock() for writers, that should blocks all access.

**Comment by adelowo** [comment]
Then i guess i'd just stick a `RWMutex`.... Thanks a lot .. I would push the changes soon

**Comment by adelowo** [comment]
Thanks a lot @raff
