### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by pundliksarafdar** [adelowo/onecache#27]
In get call we are getting panic error randomly, here is the stack trace

goroutine 1549 [running]:
runtime.throw(0xc451b2, 0x21)
/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000b16600 sp=0xc000b165d0 pc=0x42bd92
runtime.mapaccess2_faststr(0xb51c20, 0xc00017f6b0, 0xc0009bc460, 0x49, 0xc00017f688, 0xc0001c8700)
/usr/local/go/src/runtime/map_faststr.go:116 +0x4a9 fp=0xc000b16670 sp=0xc000b16600 pc=0x412589
github.com/adelowo/onecache/memory.(*InMemoryStore).Delete(0xc00017f680, 0xc00029a400, 0x40, 0x49, 0xc0001c87d8)
/jenkins/workspace/Vega_1.0.0_Nightly_Build/pkg/mod/github.com/adelowo/onecache@v0.0.0-20190301175940-21e89ccbf689/memory/memory.go:84 +0x70 fp=0xc000b166b0 sp=0xc000b16670 pc=0x59f330
github.com/adelowo/onecache/memory.(*InMemoryStore).Get(0xc00017f680, 0xc00029a400, 0x40, 0x10, 0x10, 0xb22820, 0xb, 0xc000b16768)
/jenkins/workspace/Vega_1.0.0_Nightly_Build/pkg/mod/github.com/adelowo/onecache@v0.0.0-20190301175940-21e89ccbf689/memory/memory.go:73 +0x16c fp=0xc000b16708 sp=0xc000b166b0 pc=0x59f20c

Added quote in below code snipet where its failing

func (i *InMemoryStore) Get(key string) ([]byte, error) {
	i.lock.RLock()

	item := i.data[i.keyfn(key)]
	if item == nil {
		i.lock.RUnlock()
		return nil, onecache.ErrCacheMiss
	}

	if item.IsExpired() {
		i.lock.RUnlock()
		**

> i.Delete(key)

**
		return nil, onecache.ErrCacheMiss
	}

	i.lock.RUnlock()
	return copyData(item.Data), nil
}

**Comment by adelowo** [comment]
@pundliksarafdar apologies for the late reply. Fixed and released `2.6.2` https://github.com/adelowo/onecache/releases/tag/2.6.2
